//
// Comments
//
pipeline {
    agent {
        label 'orion'
    }
    options {
        disableConcurrentBuilds()
        timestamps()
    }
    
    stages {
        stage ('Verify Parameters') {
            steps {
                echo 'Verify Parameters'
                echo "Base URL   is ${JENKINS_URL}"
                echo "Git URL    is ${GIT_URL}"
                script {
                    removeGitHubInfo()
                    if (env.ghprbPullId != null) {
                        echo "======= THIS IS A PULL REQUEST ======"
                        echo "PR ID      is ${env.ghprbPullId}"
                        echo "PR LINK    is ${env.ghprbPullLink}"
                        echo "PR TITLE   is ${env.ghprbPullTitle}"
                        echo "PR SRC BR  is ${env.ghprbSourceBranch}"
                        echo "PR TRG BR  is ${env.ghprbTargetBranch}"
                        echo "PR SRC COM is ${env.ghprbActualCommit}"
                        echo "PR TRG COM is ${GIT_COMMIT}"
                        sh "git log -n1"
                        // Going on the source branch and commit
                        sh "git checkout -f ${env.ghprbActualCommit}"
                        sh "git log -n1"
                        // Making a hard copy of the SHA-ONE
                        getCommitSha()
                        sh "git config user.email \"jenkins@openairinterface.org\""
                        sh "git config user.name \"OAI Jenkins\""
                        // Doing a temporary merge w/ target branch
                        sh "git merge --ff ${GIT_COMMIT} -m \"Temporary merge for CI -- ${env.ghprbSourceBranch} to ${env.ghprbTargetBranch}\""
                        sh "git status"
                        sh "git log -n1"
                    } else {
                        echo "======= THIS IS A PUSH EVENT ======"
                        echo "Git Branch is ${GIT_BRANCH}"
                        echo "Git Commit is ${GIT_COMMIT}"
                        // Making a hard copy of the SHA-ONE
                        getCommitSha()
                    }
                }
            }
        }
        stage ('Compile') {
            steps {
                dir('src') {
                    sh "gcc -o ../bin/test1 test1.c"
                    sh "gcc -o ../bin/test2 test2.c"
                    sh "cppcheck --enable=warning --force --xml --xml-version=2 . 2> ../cppcheck.xml"
                }
            }
        }
        stage ('Test') {
            steps {
                sh "cd $WORKSPACE; bin/test1"
                sh "cd $WORKSPACE; bin/test2"
            }
        }
    }
    post {
        always {
            updateGithubCommitStatus(currentBuild)
        }
        success {
            script {
                if(fileExists('cppcheck.xml')) {
                    archiveArtifacts artifacts: 'cppcheck.xml'
                }
            }
        }
    }
}

def removeGitHubInfo() {
  if (fileExists('.git/remote-url')) {
    sh "rm -f .git/remote-url"
  }
  if (fileExists('.git/current-commit')) {
    sh "rm -f .git/current-commit"
  }
}

def getRepoURL() {
  if (!fileExists('.git/remote-url')) {
    sh "git config --get remote.origin.url > .git/remote-url"
  }
  return readFile(".git/remote-url").trim()
}
 
def getCommitSha() {
  if (!fileExists('.git/current-commit')) {
    sh "git rev-parse HEAD > .git/current-commit"
  }
  return readFile(".git/current-commit").trim()
}
 
def updateGithubCommitStatus(build) {
  // workaround https://issues.jenkins-ci.org/browse/JENKINS-38674
  repoUrl = getRepoURL()
  commitSha = getCommitSha()
  jobMsg = "no message"
 
  step([
    $class: 'GitHubCommitStatusSetter',
    reposSource: [$class: "ManuallyEnteredRepositorySource", url: repoUrl],
    commitShaSource: [$class: "ManuallyEnteredShaSource", sha: commitSha],
    errorHandlers: [[$class: 'ShallowAnyErrorHandler']],
    statusResultSource: [
      $class: 'ConditionalStatusResultSource',
      results: [
        [$class: 'AnyBuildResult', state: build.currentResult, message: jobMsg]
      ]
    ]
  ])
}
