// Comments
pipeline {
    agent {
        label 'orion'
    }
    options {
        disableConcurrentBuilds()
        timestamps()
    }
    
    stages {
        stage ('Verify Parameters') {
            steps {
                echo 'Verify Parameters'
                echo "Base URL   is ${JENKINS_URL}"
                echo "Git Branch is ${GIT_BRANCH}"
                echo "Git Commit is ${GIT_COMMIT}"
                echo "Git URL    is ${GIT_URL}"
            }
        }
        stage ('Compile') {
            steps {
                dir('src') {
                    sh "gcc -o ../bin/test1 test1.c"
                    sh "cppcheck --enable=warning --force --xml --xml-version=2 . 2> ../cppcheck.xml"
                    //shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
                    //echo "shortCommit is ${shortCommit}"
                }
            }
        }
        stage ('Test') {
            steps {
                sh "cd $WORKSPACE; bin/test1"
            }
        }
    }
    post {
        success {
            script {
                if(fileExists('cppcheck.xml')) {
                    archiveArtifacts artifacts: 'cppcheck.xml'
                }
            }
        }
    }
}
